services:
  cache:
    image: redis:7.2.3-alpine
    container_name: cache-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      app-tier:

  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    image: gabcares/sepsis-fastapi:latest
    container_name: fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 7860
    volumes:
      - src:/src
    ports:
      - "7860:7860"
    env_file:
      - path: ./env/offline.env
        required: true
      - path: ./env/online.env
        required: false
    depends_on:
      - cache
    networks:
      app-tier:

  client:
    build:
      context: ./src/client
      dockerfile: Dockerfile
    image: gabcares/sepsis-streamlit:latest
    container_name: client-streamlit
    command: streamlit run app.py
    volumes:
      - client:/client
    ports:
      - "8501:8501"
    env_file:
      - path: ./env/offline.env
        required: true
      - path: ./env/online.env
        required: false
    depends_on:
      - api
    networks:
      app-tier:

networks:
  app-tier:
    driver: bridge

volumes:
  src:
  client:
  redis_data: {}
